version: '3.8'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pmt
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
     - backendNetwork

  backend:
    build:
      context: ./backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/pmt?useSSL=false&allowPublicKeyRetrieval=true&connectionTimeout=30000&socketTimeout=30000
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    volumes:
      - ./backend/logs:/app/logs
    networks:
      - backendNetwork
      - frontendNetwork

  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:80"
    environment:
      - API_URL=http://backend:8080
    depends_on:
      - backend
    volumes:
      - ./proxy.docker.conf.json:/app/proxy.conf.json
    networks:
      - frontendNetwork

volumes:
  db_data:

networks:
  backendNetwork:
  frontendNetwork:
