describe('Test5', () => {
  it('taskHistory', () => {
    cy.visit('http://localhost:4200/')
    cy.get('#email').type('testMouheb1@test.com')
    cy.get('#password').type('test')
    cy.get('.submit-btn').click()
    cy.get(':nth-child(16) > .project-header > .project-actions > .action-buttons > .btn-details').click()
    cy.get('h1').should('contain', 'projectMouheb1')
    cy.get(':nth-child(1) > .task-list > :nth-child(1)').click()
    cy.get('.btn-edit').click()
    cy.get('#name').type('testTaskUpdate')
    cy.get('.btn-save').click()
    cy.get(':nth-child(1) > .task-assignment > .task-actions > .btn-history').click()
    cy.get('.history-details').should('contain', 'testTasktestTaskUpdate')
    cy.get('.close-btn').click()
    cy.get('.project-actions > :nth-child(2)').click()
    cy.get('.logout-btn').click()
    })
})